spring:
  application:
    name: basicboardv1
  datasource:
    url: jdbc:mysql://localhost:3306/java_basic?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
server:
  port: 8082
mybatis:
  mapper-locations: classpath:mybatis/*.xml
  type-aliases-package: com.example.spring.basicboardv1.model