apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
  labels:
    db: polar-rabbitmq
data:
  rabbitmq.conf: |
    default_user = user
    default_pass = 1234
    vm_memory_high_watermark.relative = 1.0 
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: polar-rabbitmq
  labels:
    app: polar-rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: polar-rabbitmq
  template:
    metadata:
      labels:
        app: polar-rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:management
          env: 
            - name: RABBITMQ_DEFAULT_USER
              value: "user"
            - name: RABBITMQ_DEFAULT_PASS
              value: "1234"
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          ports:
            - containerPort: 5672  # AMQP 포트
            - containerPort: 15672 # Management UI 

---

apiVersion: v1
kind: Service
metadata:
  name: polar-rabbitmq
  labels:
    db: polar-rabbitmq
spec:
  type: ClusterIP
  selector:
    db: polar-rabbitmq
  ports:
  - name: amqp
    protocol: TCP
    port: 5672
    targetPort: 5672
  - name: management
    protocol: TCP
    port: 15672
    targetPort: 15672