apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  labels:
    app:  order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  order-service
  template:
    metadata:
      name:  order-service
      labels:
        app:  order-service
    spec:
      containers:
        - name:  order-service
          image: nginx
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ] # 쿠버네티스가 서비스를 살릴때 쓰느 명령어?
          ports:
            - containerPort: 9002

          env:
            - name: SPRING_R2DBC_URL
              value: r2dbc:mysql://polar-mysql:3306/order

      