
services:
  catalog-service:
    build:
      context: C:\Users\elec1\Desktop\java_2\polar-service\catalog-service
      dockerfile: Dockerfile
    depends_on:
      - polar-mysql
    image: "catalog-service"
    container_name: "catalog-service"
    ports:
      - 8001:9001
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://polar-mysql:3306/catalog?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8

  polar-mysql:
    image: "mysql:latest"
    container_name: "polar-mysql"
    ports:
      - 3308:3306
    environment:
      - MYSQL_ROOT_PASSWORD=1234     
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
