
services:
  auth-service:
    build:
      context: C:/Users/elec1/Desktop/java_2/polar-service/auth-service
      dockerfile: Dockerfile
    image: "auth-service"
    container_name: "auth-service"
    ports:
      - 9004:9004
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://polar-mysql:3306/auth?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      

  dispatcher-service:
    build:
      context: C:/Users/elec1/Desktop/java_2/polar-service/dispatcher-service
      dockerfile: Dockerfile
    image: "dispatcher-service"
    container_name: "dispatcher-service"
    ports:
      - 9003:9003
    environment:
      - SPRING_R2DBC_URL=r2dbc:mysql://polar-mysql:3306/order
      - ORDER_SERVICE_URL=http://order-service:9002
      - CATALOG_SERVICE_URL=http://catalog-service:9001
      - RABBITMQ_HOST=polar-rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=user
      - RABBITMQ_PASSWORD=1234
      

  edge-service:
    build:
      context: C:/Users/elec1/Desktop/java_2/polar-service/edge-service
      dockerfile: Dockerfile
    image: "edge-service"
    container_name: "edge-service"
    ports:
      - 9000:9000
    environment:
      - CATALOG_SERVICE_URL=http://catalog-service:9001
      - ORDER_SERVICE_URL=http://order-service:9002
      - DISPATCHER_SERVICE_URL=http://dispatcher-service:9003
      - AUTH_SERVICE_URL=http://auth-service:9004

  order-service:
    build:
      context: C:/Users/elec1/Desktop/java_2/polar-service/order-service
      dockerfile: Dockerfile
    depends_on:
      - polar-mysql
    image: "order-service"
    container_name: "order-service"
    ports:
      - 8002:9002 
    environment:
      - SPRING_R2DBC_URL=r2dbc:mysql://polar-mysql:3306/order
      - CATALOG_SERVICE_URL=http://catalog-service:9001

  catalog-service:
    build:
      context: C:\Users\elec1\Desktop\java_2\polar-service\catalog-service
      dockerfile: Dockerfile
    depends_on:
      - polar-mysql
    image: "catalog-service"
    container_name: "catalog-service"
    ports:
      - 8001:9001
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://polar-mysql:3306/catalog?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      

  polar-mysql:
    image: "mysql:latest"
    container_name: "polar-mysql"
    ports:
      - 3308:3306
    environment:
      - MYSQL_ROOT_PASSWORD=1234     
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

  polar-rabbitmq:
    image: "rabbitmq:management" #대시보드를 사용하기 위해 management 태그를 사용
    container_name: "polar-rabbitmq"
    ports:
      - 5672:5672 #서버포트
      - 15672:15672 #대시보드 포트
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=1234
    volumes: #컨테이너 내부의 설정파일을 호스트에 연결
        - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
