spring:
  application:
    name: basic-board-test-v2

  datasource:
     url: jdbc:mysql://localhost:3306/java_basic?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
     driver-class-name: com.mysql.cj.jdbc.Driver
     username: root
     password: 1234

server:
  port: 8084

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.example.spring.basicboardtestv2.model



