server:
  port: 9004

spring:
  application:
    name: auth-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3308/auth?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.practice.spring.authservice.model

jwt:
  issuer: elec1001@gmail.com
  secret_key:  O4SxPzNI26ON9JzP9Yx1ffnBKucULNdrUrL0t114BdgRmvKGFGT9RnLp8BP1MG+RosB46Tb6V7WjeSKM/1EN2Q==