server:
  port: 9000

spring:
  application:
    name: edge-service
  cloud:
    gateway:
      routes:
        - id: catalog-service
          uri: ${CATALOG_SERVICE_URL:http://localhost:9001}/books
          predicates:
            - Path=/books/**
          filters:
            - name: CircuitBreaker
              args:
                name: catalogCircuitBreaker
                fallbackUri:  forward:/service-fallback # WebEndPoints ????? ??

        - id: order-service
          uri:  ${ORDER_SERVICE_URL:http://localhost:9002}/orders
          predicates:
            - Path=/orders/**
          filters:
            - name: CircuitBreaker
              args:
                name: orderCircuitBreaker
                fallbackUri: forward:/service-fallback # WebEndPoints ????? ??


resilience4j:
  circuitbreaker:
    configs:
      default:
        permitted-number-of-calls-in-half-open-state: 5 #??? ??? ???? ???? ??? ?
        failure-rate-threshold: 50 #???? ??? ???? ??? ??(??? ??) ??? ???
        wait-duration-in-open-state:  15000 #?? ???? ??? ??? ???? ??? ??(???)
  timelimiter:
    configs:
      default: #?? ?? ??? ?? ?? ??
        timeout-duration:
          seconds: 5
